### ISSUE TITLE
Es file explorer 

### ISSUE THREAD

**Issue by jctang1028** [silentshadow88/Custom-Wallpaper-for-Proton-X50-Atlas-OS#1]
I was wondering es file explorer can use for install other apk in atlas or just change wallpaper only? Anyone tried?

**Comment by silentshadow88** [comment]
There is modified code in the standard package installer that prevents apps from being installed from sources other than the designated source.Btw there are solutions to remove this code, but they come with a risk of causing a bootloop or getting stuck on boot.

**Comment by jctang1028** [comment]
> There is modified code in the standard package installer that prevents apps from being installed from sources other than the designated source.Btw there are solutions to remove this code, but they come with a risk of causing a bootloop or getting stuck on boot.

I see, so is not recommend to sideload other apps via es file explorer

**Comment by silentshadow88** [comment]
> > There is modified code in the standard package installer that prevents apps from being installed from sources other than the designated source.Btw there are solutions to remove this code, but they come with a risk of causing a bootloop or getting stuck on boot.
> 
> I see, so is not recommend to sideload other apps via es file explorer

u can try but end up it wont install as default installation folder is on data/app which is control by some code that verified signature from apk..
