### ISSUE TITLE
uninstall code

### ISSUE THREAD

**Issue by putradunn** [silentshadow88/Custom-Wallpaper-for-Proton-X50-Atlas-OS#2]
Hi Sifu

can you provide uninstall code ?

In case HU problem & need to bring to SC for repair & etc

TQ

**Comment by silentshadow88** [comment]
> Hi Sifu
> 
> can you provide uninstall code ?
> 
> In case HU problem & need to bring to SC for repair & etc
> 
> TQ

repo updated,download file updated..otherwise you can disabled ES at open hidden setting>apps>all and find es file manager

**Comment by silentshadow88** [comment]
closed
